name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 7am UTC3
    - cron: "0 4 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "True"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE : "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LOC_CHART: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_OS: "True"
          LOCALE: "en"
