name: Calendar Update

on:
  workflow_dispatch:
  schedule:
    # Runs every half hour
    - cron: "*/30 * * * *"

jobs:
  update-calendar:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # ... other options
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
