name: Calendar Update

on:
  workflow_dispatch:
  schedule:
    # Runs at 7am UTC3
    - cron: "0 4 * * *"

uses: lowlighter/metrics@latest
  with:
    # ... other options
    plugin_isocalendar: yes
    plugin_isocalendar_duration: full-year # Display full year instead of half year
