name: Calendar Update

on:
  workflow_dispatch:
  schedule:
    # Runs every half hour
    - cron: "*/30 * * * *"

jobs:

  update-calendar:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          filename: metrics.plugin.isocalendar.fullyear.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: commit
          delay: 120
